_config_prod.yml, _config_staging.yml, _includes/footer.html, scripts/cibuild
- Removed the non-working links from the footer (footer subject to change anyway, so these links are currently 'placeholder' anyway)
- Updated the production and staging versions of the config file
- Generated the jekyll build with the production version of the config file. Html-proofer was generating lots of errors, related to this [issue with baseurl](https://github.com/gjtorikian/html-proofer/issues/266) and some suggested workarounds didn't improve matters.
=> This should resolve html-proofer build issues

_config.yml, _indicators/14-2-1.md, _layouts/indicator.html
- Updates the prose configuration and indicator.html to support a `national` scope.
- Adds a third data source (turned off by default)
- Remove unused (at least in the UK) metadata fields from prose config
=> Add national level metadata

assets/js/indicatorModel.js
The `years` variable was never sorted correctly, because the anonymous function was incorrect. By that point in the chain, it was a string, so didn't have the `Year` property. All values for sorting were therefore `undefined`.
The issue was found because the 'all' year data was a subset of subsequent `year` values, so the years were returned 'as found'.
Sorting is now done correctly.
=> Fixes Unordered X Axis labels on plots

_includes/scripts.html
Jekyll generated timestamp so new releases are deemed 'updated' by browsers.
=> Cache busting for assets

_config.yml, _indicators/14-1-1.md, data/indicator_14-1-1.csv, scripts/demo14.R, scripts/metadatacheck.py
- Adds a continent category which is a child of planet
- Add `data_edge_list` to meta data, which is a string specifying a parent child edge list `"P1:C1,P2,C2,..."`
Parents are children are listed by their column index (counting from 0). So for the demo data set this is `2:3` which indicates that column 2 (Planet) is the parent of 3 (Continent)
=> Fixes #124 add hierachical data

assets/js/indicatorModel.js
Added a 'to 3 significant figures' rounding function to the `indicatorModel`, which can be overridden by passing in a function.
=> Rounding function for charts/tables

_includes/components/charts/chart.html, _includes/scripts.html, _layouts/indicator.html, assets/js/indicatorModel.js, assets/js/indicatorView.js
This implements the changes required for #112. If no source is found, then 'Source: ' is still shown on the graph, as can be seen on this [ONS graph](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/lf24/lms). I do a similar thing for 'Geographical area'. Both are at the bottom right of the graph.
I moved the legend to the bottom of the graph, which is more in keeping with the example given above, and doesn't clutter the title area.
The y axis label is not oriented horizontally - in some cases, such as 'percentage' a horizontal orientation would result in an unnecessarily narrow graph, so I went with the default orientation.
On a technical note, I've added more data-* attributes to the #indicatorData element, and although this is fine, I …
=> Data source and other chart mods

assets/js/indicatorModel.js
The rounding function discarded negative numbers by converting them to NaN.
A `Math.abs(...)` call resolves the issue.
=> Negative numbers not discarded by rounding function

Gemfile, _layouts/frontpage.html, _layouts/goal.html
This fixes #281.
[GitHub updated their version of Jekyll to 3.5.1](https://pages.github.com/versions/) on Tuesday, 8th August.
This caused an issue with the `cycle` liquid tag, and the issue can be reproduced locally by updating `Gemfile` jekyll version to 3.5.1 and running `bundle update` from the command line.
To fix the issue, I changed the `nil` parameters in the `cycle` tag to empty strings.
=> Home page row cycles fix 

_includes/components/dev-disclaimer.html, _includes/header.html, _includes/search.html, assets/css/default.scss, assets/js/menu.js, assets/js/sdg.js
This fixes #291 as well as vastly improving the 'skip to content' accessibility link.
1 - The 'Skip to main content' link is now much more prominently displayed.
2 - As shown in #291, the menu/search was broken in lower viewports. This PR fixes those issues, and is visually very similar to that of the main [ONS site](https://www.ons.gov.uk/). Gone is the fixed header that reduces in height as the user scrolls down, but I think that this wasn't really needed, and the larger header height was regarded as too large by some anyway.
=> Responsive menu/search

_layouts/reportingstatus.html, assets/css/default.scss, assets/js/reportingStatus.js
I have removed the animation too - it looked alright when I first did it, but having seen it a few times now, find it a little annoying.
More importantly, the initial viewport width isn't used to set the widths of the elements. CSS `calc(...)` is now used, so it responds to viewport width changes; other tweaks have been made to make things look good at other viewport widths too.
=> Reporting status now responds to viewport width changes

_layouts/reportingstatus.html, assets/js/reportingStatus.js
This fixes #326, which is part of #307 and allows users to view reporting status information _without_ JavaScript.
In terms of progressive enhancement, JS adds percentages text _and_ coloured bars. Why aren't these static? Well, it seems that Liquid does some unfortunate rounding, so percentages may not add up to 100. I made a decision to give people the information they needed, but put a bit of 'icing on the cake' to finish things off for those with JS enabled.
Without JS, the page looks like the screenshot, above.
=> Reporting status works without JavaScript enabled

_includes/scripts.html
Version 2.7 ditches the `iframe`, so the accessibility issues has gone.
=> Update to chart.js version 2.7 fixes #338

_includes/scripts.html, assets/js/indicatorView.js
Chart height was based on screen height, and the previous code for deriving the chart height wasn't quite right for devices with smaller vertical resolutions.
Hopefully this resolves things.
=> Charts - ooh haven't you grown!

_includes/components/headline.html, _layouts/indicator.html, assets/js/indicatorModel.js
* Table is built in `_includes/components/headline.html`
* Table is added to the `#datatables` div which is automatically overwritten when JS fires up
* Changed "Headline for UK" to "Headline data"
Seeing how this looks pretty good I wonder if we disable the JavaScript override for now? We needed it when we had the pivot tables but it's not doing much anymore.
=> Fixes #388 adds headline viewable without js

_includes/components/fields-template.html, _includes/scripts.html, assets/css/default.scss, assets/js/indicatorModel.js, assets/js/indicatorView.js
Children are shown immediately; not only their 'headings', but also their possibilities. Children are indented underneath their parents and when no parent items are selected, a hint is shown and the items aren't selectable. Select a parent and the child's items are selectable (and the hint disappears).
Hopefully this PR shows no-nonsense help and intuitive relationships between data items.
=> Showing children 

_layouts/goal.html
and close div accordingly. to solve the issue of having too many closing div tags if the end of the row closes the div twice.
=> Test if number of indicators is divisible by 4 

assets/js/indicatorModel.js
Turns out the filtering wasn't quite right. For the 'category' filtering, I wasn't correctly using the previously filtered data! I saw @AnnCorp's comment, https://github.com/datasciencecampus/sdg-indicators/issues/1184#issuecomment-341708374, and this fix has resolved that issue too.
=> Units should now be sorted when selecting category

_layouts/indicator.html
This PR moves the page content into a row above the chart so that it spans the page. I've also removed the sub-categories div if the `show_data flag` is false
Fixes #1166
=> Page content in separate row

_includes/components/metadata.html, assets/css/default.scss
With visually hidden span tag telling screen readers 
Fixes #1074 
It's actually all metadata links that will open in a new window/tab. This doesn't seem such a bad thing anyway, and helps accessibility.
=> pdfs in new window

assets/js/indicatorModel.js, assets/js/indicatorView.js, data/edges/edges_11-6-2.csv
This PR resolves a number of issues relating to the lack of headline data. 
The code expected there to be headline data, but carried on if it didn't find any. However, plotting an empty array as a series caused some issues when showing other data series on the same chart. (#516 and #1202)
The changes identify that headline data is not present (it also takes into account the 'unit of measurement' if it is relevant) and automatically selects the _first_ item for the _first_ 'category'.
=> No headline data, no problem

assets/js/indicatorModel.js
This fixes the 'where are my 0s?' I tracked it down to the rounding function, which should not be allowed to work with 0s. It was changing them to `NaN`s.
=> 0 to hero (0s are now shown on the charts)

assets/css/default.scss
There was an issue with overlapping nav elements between 769 and 991 pixels viewport width.
This PR moves seems to fix the issue.
=> Fixes overlapping nav elements at 'medium' viewport widths

_includes/components/fields-template.html, assets/css/default.scss, assets/js/indicatorModel.js, assets/js/indicatorView.js
Here's a possible approach to #1204. I'm new to underscore and this project both, so there are probably more efficient ways to do this. Just throwing this out there in case it helps get the ball rolling. Also some notes:
* This includes CSS to hide the field items without data, but it could be changed to disable them instead.
* More work needed: there should also be some indication of when a child field has 0 available items, similar to the "Selectable when..." message. This could be either hiding the child field altogether (the whole dropdown) or some message like "No options available for this set of filters".
=> Hide all child field values that don't have data

assets/css/default.scss, assets/js/menu.js
I fixed the 'search' heading text with some extra code. I'm sure this was working before, but the steps to reproduce were:
1 - Click Search (note that the heading changes to 'hide')
2 - Click menu (search disappears, as expected)
3 - Click Search and observe correct behaviour (as in step 1)
4 - Click Search and observe that text stays as 'hide')
Step 4 is no more.
=> Fixes mobile menu 'Search' heading

assets/css/default.scss
As it turns out, lower viewport widths still suffer a little from the 'space under the icon' issue, although I don't think it's as bad as it was before because the font size has been reduced at lower viewport widths.
The smaller font also means that the slash/wrap/issue has gone away, although if/you/wanted/more/slashes/in/your/title/the/problem/may/return. However, I think that generally, we won't come across such a long heading. (Unless somebody knows different).
=> Fixes mobile indicator heading slash/wrap/issue

assets/js/indicatorModel.js
`slice`ing is done further down in the code for the `datasets` variable based on whether the count exceeds the `maxDatasetCount` value.
The table data is currently not restricted.
=> Allows more than 13 columns for disaggregation in the Table tab

_includes/scripts.html, _layouts/indicator.html, assets/css/default.scss
* Global Netadata and National Metadata tab
* Removed collapsible sections (including js in scripts.html). This hopefully simplifies a few accessibility issues we were having.
See https://mangothecat.github.io/sdg-indicators/3-3-2/ for a live example.
=> Move global metadata into its own tab #2022 

scripts/reset/reset_metadata.py
Fixes #2354 
Adds a script that keeps anything in `page`, or `global` scope. Sets `reporting_status: 'notstarted'` and drops everything else from the `_indicators/*.md` files
=> Reset the metadata

_includes/components/charts/chart.html, _includes/scripts.html, assets/css/default.scss, assets/js/indicatorView.js
This PR resolves #2339 by generating the legend content as html.
Whilst trying to keep everything look as it did before (except for the deficiencies outlined in #2339), generating the html ourselves has the benefit that I am able to add a hover style for legend items, and I dare say that now we have control over the legend text, we can possibly do other things that using the 'default' legend generation didn't permit us to do.
No two ways about it though, 3.2.2 can generate some really long legend titles, and although the clipping has been solved, it still results in a hefty legend.
e4d4082 changes the style for 'dashed' chart items. I think this is clearer than what we had before, but others may disagree.
=> Tidier legend

_config.yml, _config_prod.yml, _includes/scripts.html, _indicators/3-9-1.md, _indicators/4-2-1.md, _layouts/indicator.html, assets/js/indicatorModel.js, assets/js/indicatorView.js
This PR results in the map being shown only when the `data_show_map` metadata is present AND set to true. (In addition, the data's GeoCode column must be present, as before.)
=> Map data_show_map metadata

scripts/build_csvs.py, scripts/build_json.py, scripts/build_metadata.py, scripts/sdg/git.py, scripts/sdg/path.py
Related to #2581. In preparation for the repo-split I'm copying over changes that I had to make on test splits. These changes are compatible with the current repo. The main idea is that in `scripts/sdg/path.y` each indicator path in `indicator_path` has a read `r` mode and a `w` write mode. The scripts are all updated so that they use the correct one. When the split is done we just need to change the base path for the read location and we're good to go.
=> Build paths

_config.yml, _config_prod.yml, _layouts/goal.html, _layouts/reportingstatus.html, _layouts/search.html
This jumps to the current head of open-sdg to pickup a bug fix to the page title. See open-sdg/open-sdg#64
Both staging and prod use commit 606b3159e2 of open-sdg. We can pick up the next release when that comes along. Given that this is a bug-fix I will push for a 0.3.1 tag.
=> pull through fix to page titles from open-sdg

.gitignore
Removing jekyll_metadata from .gitignore - this is a similar problem we saw with [Rwanda](https://github.com/sustainabledevelopment-rwanda/sdg-indicators/commit/3b20f34a380257397c672cb117caa845d0ebef24), which prevented updates from displaying. I don't know why this value is generated. https://github.com/ONSdigital/sdg-indicators/issues/2920
=> Fix feature branch metadata issue...?

_config.yml
Simply replace these fields with http://sdg.mango-solutions.com/data/featurebranch.
Note the quote marks (remotedatabaseurl) and apostrophes (jekyll_get_data) used.
=> Set up data-deploy branch (TAKE 2)

_config.yml
=> Update mapping zoom levels

_config.yml
Country boundaries added to open-sdg map, and zooming overlaps enabled.
Disabling them for now, but we have them on backup now.
To revert, set minZoom to 5 and uncomment lines 125-30.
=> Map features (see description)

_layouts/indicator.html
Follow up to #3026 to pull back small divergences between our indicator.html and the open-sdg version.
=> merge open-sdg indicator.html with ONS mods

_layouts/indicator.html
Removing `{% include polyfill.html %}` as this didn't work as expected.
The file is still stored in [_includes](https://github.com/ONSdigital/sdg-indicators/blob/develop/_includes/polyfill.html)
=> Remove polyfill.html

_includes/assets/js/indicatorView.js
Disaggregation checkboxes were losing focus due to a weird quirk of `jQuery`'s `.appendTo()` function. I think this should fix the issue. Screen readers should now also announce when the checkboxes are being ticked or unticked.
Test URL: https://sdg.mango-solutions.com/a11y-checkbox-focus-fix/
=> [Accessibility] Checkbox screen reader fix

_includes/assets/js/indicatorView.js
The `aria-expanded` label updates when a disaggregation is expanded or collapsed so the screen reader notifies the user.
=> [Accessibility] Add aria-expanded label updating to disaggregations

data/translations/en/header.yml
This change replaces the survey link at the top bar with the one from Phill. It also replaces the text for the survey.
Test link: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/new_survey_link/
=> Replace survey link at top bar

_includes/components/indicator/indicator-content.html
Automatically generate CSV download text and link in catch-all text section when indicator is reported and non-statistical. When indicator is not reported, generate some text.
=> Overwrite indicator-content.html

.github/workflows/accessibility.yml, scripts/accessibility-test/config/high-contrast.json, scripts/accessibility-test/run_tests.sh
This change uses Github Actions to run accessibility tests using Pa11y. This is a response to [this Trello card](https://trello.com/c/CviKnpSQ).
During the action:
1. The repo gets checked out at the specific branch
2. Ruby and NodeJS get installed
3. The Jekyll website gets built
4. Pa11y gets installed via `npm`
5. Pa11y tests are run on a selection of websites and configurations
We have previously made a list of pages with special features in order to test them for accessibility. As the accessibility issues haven't been fixed, and this pull request is for adding the tests to run and complete, I have omitted some of the pages. For now, these pages get tested for accessibility:
* Home
* Goal 1
* About
* Reporting status
* FAQ
* Updates
* Accessibility statement
=> Run Pa11y tests on each pull request using Github Actions
