_includes/components/charts/bar.html
_includes/components/charts/line.html
_includes/scripts.html
_layouts/indicator.html
assets/js/chartDataProcessor.js

Chart data series and labels generation are delegated to the `chartDataProcessor` object, making the chart code simpler and more reusable across chart types.

multi series graphs

---

_config.yml
_indicators/14-2-1.md
_layouts/indicator.html

- Adds the sources to the prose configuration
- Renders active sources on the page

Sources metadata for #36

---

_includes/head.html
assets/css/default.scss
assets/js/dataManager.js

This PR addresses issue #47 where missing data was not handled correctly.
An example of what's produced is shown below:

Missing data handled correctly in plots

---

_config.yml
_includes/components/metadata.html
_includes/components/sources.html
_layouts/indicator.html

Adds a separate tab for data sources. Contributes to #58

Move sources to their own tab

---

scripts/csvcheck.rb

And more verbose error message

Fixes #74 strip whitespace from value field.

---

_includes/components/metadata.html
_includes/components/sources.html
_includes/scripts.html
_layouts/indicator.html
assets/css/default.scss

implements #62.
assumption that the first metadata section, 'Global', will initially be
shown in an expanded state.

Collapsible metadata sections

---

_includes/scripts.html
assets/js/sdg.js

using `include_relative` liquid tag for simple merge of `event.js`, `indicatorModel.js`, `indicatorView.js` and `indicatorController.js`.
3 fewer HTTP requests.

3 fewer JS HTTP requests

---

assets/js/indicatorModel.js

toned down the black and tweaked the other colours.

tweaked chart colours

---

_includes/components/dev-disclaimer.html
_includes/header.html
_layouts/frontpage.html
_layouts/goal.html
_layouts/indicator.html
_layouts/page.html
_layouts/reportingstatus.html
assets/css/default.scss

Implements the tasks for #117.

Shorten and move disclaimer notice

---

_layouts/frontpage.html
assets/css/default.scss

Some padding/margin around the home page goals, simple hover effect. Subject to review.

Home page UI

---

_includes/components/charts/chart.html
_includes/components/charts/line.html

Fixes overlap between plot and other info when there are lots of disaggregations

---

_config.yml

Add defitions to computation scope

---

_config.yml

definitions is a textarea in prose

---

_includes/components/metadata.html
_indicators/3-2-1.md

Only display the default link if the url is not empty

Fixes #109 so that empty sources don't display default link

---

assets/js/search.js

Search string escaped for regex match

---

_includes/components/fields-template.html
assets/css/default.scss
assets/js/indicatorModel.js
assets/js/indicatorView.js

Disaggregation drop down 'selected' indicators

---

_layouts/reportingstatus.html
assets/js/reportingStatus.js

I have added hyperlinks for the goal images and headings.
Also, I was aware that the existing percentage calculations for a goal's statuses may not sum to 100. I have introduced a new algorithm so they do.

Reporting status fixes and enhancements

---

_layouts/reportingstatus.html
assets/css/default.scss
assets/js/reportingStatus.js

This implements #315, together with the numbers for each reporting status type (beforehand, just percentages were shown.)

Overall reporting status

---

_includes/footer.html
assets/css/default.scss

I've kept a footer, because I think _something_ will need to go in it, but I have removed the ONS links.
Future changes will be easier to incorporate though, and hopefully what's there now is less contentious.

Trimmed down footer

---

_includes/header.html
_includes/search.html
_layouts/frontpage.html
_layouts/goal.html
_layouts/indicator.html
_layouts/reportingstatus.html
assets/css/default.scss
assets/js/menu.js

I reviewed the website using the aXe and WAVE extensions for Google Chrome.
This PR addresses a number of issues that were found:
- Elements must have sufficient color contrast
- Form elements must have labels
- Headings must not be empty
- Long alternate text (for images)
- Missing first level heading
The color contrast issue was quite prevalent, but some CSS changes resolved all those issues.
I'm not claiming this has fixed all the accessibility issues, but things have improved.

Accessibility improvements

---

_layouts/indicator.html

Rename method of computation

---

_layouts/goal.html
assets/css/default.scss

The changes are there, but it's not particularly clear that the text is describing the reporting status (and what that actually is)... perhaps we need some additional text somewhere?

Reporting status by indicator on goal page

---

_layouts/goal.html
assets/css/default.scss

Based on [this comment from @AnnCorp](https://github.com/datasciencecampus/sdg-indicators/issues/320#issuecomment-331434280).

Design tweaks for reporting status (#320)

---

_layouts/indicator.html
assets/css/default.scss

style table and add hr after non-empty page content

---

_config.yml
_includes/scripts.html
_layouts/indicator.html
assets/js/indicatorModel.js
assets/js/indicatorView.js

Hi @dougmet - I took your branch for 286 and added the code that conditionally renders the chart based on the `data-showdata` attribute.

Show data/non statistical metadata

---

_includes/header.html
assets/css/default.scss
assets/js/search.js

Search only shown with JS enabled

---

_includes/header.html
about.md

Fixes #314 
- Adds an about page.
- Removes front page link to news (but leaves it for when it's ready).
Hold off merge until content arrives.

[WIP] Add about page, remove link to news #314

---

about.md

added initial about info

---

_includes/components/charts/chart.html
_includes/components/units-template.html
_layouts/indicator.html
assets/css/default.scss
assets/js/indicatorModel.js
assets/js/indicatorView.js
data/indicator_9-2-1.csv

Apart from a few UI improvements (that I'll tackle in another PR), this _should_ be what's needed.
I've changed the `csv` data, renaming the column to 'Units'. If found, this column is treated as a special case - the unique values used for the radio buttons in the UI.
The 'selected unit' is the first of any that are found, so the graph default to this. The 'headline' table, however, lists the data with all the units, ordered by unit. (So you get all the years for one unit, then all the years for the other unit, and so on.)

Units of measure

---

_includes/components/fields-template.html
assets/css/default.scss
assets/js/indicatorView.js

This fixes a number of issues: #240, #351, #513.
The field 'dropdowns' should be a lot nicer now, with the 'select all' and 'select none' buttons. I also fixed the (newly created I think, but known about) 'selection bar' issue, where the bar would not always clear when all selections for that field were removed.
Please take a look at it and let me know your thoughts! Cheers.

Fields, selections, bars and easier selecting

---

data/indicator_3-2-2.csv
data/indicator_3-c-1.csv
scripts/build/csvcheck.py
scripts/build/win_environment.yml

Check whitespace in column names

---

_layouts/indicator.html
assets/css/default.scss
assets/js/indicatorView.js

E/489 - Fix text for download CSV button

---

_includes/footer.html

Release: Uncomment google analytics code

---

_includes/header.html
assets/css/default.scss
publications.md

Changed navbar-menu and navbar-brand padding and width rules to solve issue with menu text wrapping.

E/558 - Update CSS for navigation

---

_includes/head.html

Disable indexing on staging. Fixes #562

---

assets/css/default.scss

Changed all absolute font sizes to relative within default.scss

Translated font sizes from 'px' to 'em'

---

assets/js/indicatorModel.js

This should hopefully resolve the category ordering - tested with 3-2-2 and things seem to be working as hoped.

Category ordering

---

_layouts/frontpage.html
_layouts/goal.html
_layouts/indicator.html
_layouts/reportingstatus.html

Changed 'Goal #' to 'Goal Title - Goal #'

Update alt captions for goal images

---

_layouts/indicator.html

Describe sub-categories panel

---

_layouts/indicator.html

add source, geography and units under table #1199

---

_includes/components/charts/chart.html
assets/css/default.scss
assets/js/indicatorModel.js
assets/js/indicatorView.js

This should resolve #1069.
The message may benefit from some tweaking, as may the colours and dash style. But all of those are simple to change.

Limit lines on charts

---

_layouts/indicator.html

Use geography label on chart headline

---

_includes/components/headline.html
_layouts/search.html
_pages/faq.md
assets/css/default.scss
assets/js/indicatorView.js

Heading structure on all pages updated to follow the h1 - h6 hierarchy

a/1063 - Update heading hierarchy

---

_layouts/indicator.html
assets/css/default.scss

Just a couple of things, but I noticed a stray `p` in the `#datatableFooter` element.
Also changed a couple of other things.

A couple of indicator page tweaks

---

_pages/publications.md
assets/css/default.scss

updated current 'ul' styling to only affect the header.

e/1614 - Restyled list items on page

---

_includes/footer.html
assets/css/default.scss

Hi @gingerbenw - would you mind taking a look at this PR? I think I've managed to get a sticky footer with CSS alone. 
I picked up your change for the footer columns.

Sticky footer

---

_layouts/indicator.html

Added bootstrap columns to fix button layout at top of chart.

Accessible button fix

---

assets/js/indicatorView.js

hi @gingerbenw - does this resolve your padding issue?

Footnote wrapping

---

_includes/scripts.html
_indicators/16-2-3.md
_indicators/6-5-2.md
_layouts/indicator.html
assets/js/indicatorModel.js
assets/js/indicatorView.js

Updated indicatorView.js to render a bar graph if graph_type is set to bar as per #353

e/353 - Render bar graph when required

---

_includes/header.html
_pages/guidance.md

E/564 - Add Guidance Page and Content

---

_includes/scripts.html

Addition of embedded user testing suite 'Loop11' as covered by Issue #1879

Updated scripts.html to include loop11

---

assets/js/indicatorView.js

Set maxBarThickness of 150px

---

assets/js/indicatorView.js

added truthy test to table parameter in createTable function

---

_includes/components/breadcrumb.html
_layouts/indicator.html

Indicator number used in breadcrumb

---

_includes/components/headline.html
assets/css/default.scss
assets/js/indicatorView.js

Fix for this issue tests for index and adds a class, `table-value`, if it is non-zero.
(I also changed the single quotes in `headline.html` to double quotes. Single are allowed, but double are used elsewhere, so better for consistency.)

All but first column in tables are right aligned

---

_includes/footer.html
_pages/cookies.md
assets/css/default.scss

Including link in footer and footer restructure. Required by #1865

Add Cookies and Privacy Statement

---

_includes/scripts.html
_layouts/indicator.html

Add keypress trigger for '.collapsible' metadata

---

_includes/components/units-template.html
_layouts/indicator.html
assets/css/default.scss

Resolves #1932 and #1928
Updated css rules for tables and unit measurements as well as generic page buttons and tabs.

Update high-contrast CSS Rules

---

_includes/components/charts/chart.html
_includes/components/headline.html
_includes/head.html
_includes/scripts.html
_layouts/indicator.html
assets/css/default.scss
assets/js/indicatorView.js

* Remove the headline data table in the bottom tabs.
* Move the static progressive enhancement version there as well.
* Rapidly hide the static version when JS is on (reduce flickering)
Fixes #1883

Data tab to table tab #1883

---

_layouts/indicator.html

Hint on clicking chart legend

---

assets/css/default.scss
assets/js/indicatorModel.js
assets/js/indicatorView.js

Adds source, geo, units, and footnote. Styles them a bit so they blend in better. For #1913 
I added all this as a separate object to the data model. Could be reusable in the chart (but doesn't add anything except a bit of refactoring).

table footer for dynamic table

---

_includes/scripts.html
_pages/faq.md

Fixed keyboard trigger in IE11

---

_includes/footer.html
_includes/header.html
assets/css/default.scss
assets/js/accessibility.js

and removed the 'flex' attribute
Relates to #1931

1931 - Changed header layout for responsiveness

---

_layouts/indicator.html
assets/css/default.scss
assets/js/indicatorModel.js
assets/js/indicatorView.js

This turned out to be a bigger amount of work than I imagined. One issue I can see so far (with 2.3.1) is that there is no 'overall' data for the _Livestock (000s)_ units. I'm guessing that in this case, the first item (for sake of argument) should be selected so that something is shown on the graph.

Unit specific fields/data

---

_pages/cookies.md

updated cookies text

---

assets/css/default.scss

update css for navbar-brand and contrast switching buttons

---

assets/js/indicatorModel.js

ce9348c reduces the max line count to 13.
6b7ead7 is a 'suggestion'. I went onto [iWantHue - Colors for data scientists](http://tools.medialab.sciences-po.fr/iwanthue/) and generated a 6 colour palette.

Max chart lines reduced to 13

---

_layouts/search.html
assets/css/default.scss
assets/js/search.js

Good suggestion @dougmet!
Thought I'd have a look at the weekend for the love of open source ;)

Indicator search indicators now with status

---

assets/js/indicatorView.js

More than one filtering box open at one time

---

assets/js/indicatorModel.js
assets/js/indicatorView.js

Selecting things should now be fine with IE9. It took a while to track things down, but I realised that removing some redundant code also fixed the issue.

Fixes IE9 selection issue

---

_config.yml
_config_prod.yml
_includes/components/headline.html
assets/js/indicatorModel.js

Unit of Measurement

---

assets/css/default.scss

New images for #2326 had subtle background colour change. This PR updates the banner colour for Goal 10.

Updates goal 10 banner colour

---

scripts/build/edge_detect.py

Ignore empty children during edge detection

---

scripts/reset/reset_csvs.py

this is still a bit fragile but the path is updated so that it works. I switched to globbing because I want to be certain all csvs are wiped out.

reset_csvs uses glob

---

_includes/footer.html

According to my suggestion of not needing to show the email address.

Footer text length reduced for mobile

---

_config.yml
_config_prod.yml
_includes/components/sources.html
_layouts/indicator.html

Closes #2077
Removes and renames multiple metadata items (only the labels, not underlying variables) and tweaks the titles on the main page.

Rationalise metadata

---

_indicators/14-4-1.md

Reverts datasciencecampus/sdg-indicators#2400

Revert "14.4.1 metadata test 8"

---

_indicators/16-1-1.md
_indicators/16-1-2.md
_indicators/16-1-3.md
_indicators/16-1-4.md
_indicators/16-2-3.md
_indicators/16-3-2.md
_indicators/16-7-1.md

long hyper links that are not in anchor tags cause overflow issues.

use hyper-links instead of bare URLs in metadata in the 16s

---

_config.yml
_config_prod.yml
_includes/components/sources.html

Fixes #2564
Sources all at the bottom now so you don't have to scroll down so far to find other fields.

add 3 more sources 

---

8-3-1.md

8.3.1 metadata upload (v3)

---

data/indicator_3-9-1.csv

Value column moved to the end.

3.9.1 CSV (GEOTEST) (v12)

---

data/indicator_3-9-1.csv

That's probably going to jinx it.

3.9.1 CSV (FINAL)

---

_indicators/3-9-1.md

Add the regex to the 3-9-1 metadata so that Scotland and Wales go blank

Scope is England for 3-9-1

---

data/indicator_3-9-1.csv

3.9.1 CSV v2

---

_layouts/goal.html

Missed the variable rename, all working now.

Footer misalignment on goal page fix

---

assets/js/plugins/jquery.sdgMap.js

Reverts ONSdigital/sdg-indicators#2831

Revert "Map test (temp)"

---

_layouts/goal.html

Reverts ONSdigital/sdg-indicators#2835

Revert "Sort indicators by specified order"

---

_pages/publications.md

Publication formatting

---

_pages/publications.md

Added info on geography accelerator project to publications page on tool

Update publications with GAP info

---

_layouts/goal.html
_layouts/reportingstatus.html
_layouts/search.html
assets/js/reportingStatus.js

Test edit to remove 'inprogress' from Reporting Status, leaving two colours. 
https://github.com/ONSdigital/sdg-data/pull/416

Reporting status edit - DON'T MERGE

---

_layouts/goal.html
_layouts/reportingstatus.html
_layouts/search.html

Reverts ONSdigital/sdg-indicators#2877

Revert "Reporting Status colour update"

---

_config.yml
_config_prod.yml

Slight config amendment to add menus

Switch to open-sdg 2

---

_config.yml
_config_prod.yml

Reverts ONSdigital/sdg-indicators#2882

Revert "Switch to open-sdg 2"

---

_config.yml
_config_prod.yml

Adding the menu option for the open-sdg build.

Open sdg menu

---

_includes/assets/js/indicatorView.js

* Create indicatorView.js
* Update indicatorView.js

Test downloadcsvevent ga (#2908)

---

_includes/assets/js/indicatorView.js
_layouts/indicator.html

Added functionality to be able to track the following events in Google Analytics:
- Change between data views i.e. Charts tab, Table tab, etc.
- Change between metadata views i.e. National Metadata, Global Metadata, etc.

Test events ga

---

_pages/guidance.md

* Update guidance.md
* Update guidance.md
* Update guidance.md
* Update guidance.md
* Update guidance.md
* Update guidance.md
* Update guidance.md
Changed links to html so that Google Analytics can track when they're being clicked
* Update guidance.md
* Update guidance.md

PUSH TO LIVE (Test guidanceevents ga (#2914))

---

scripts/deploy/deploy_testing.sh

* use `TEST_SERVER` instead of `TEST_USER_SERVER` to try to hide IP
* compress scp traffic to speed up deployment

Enhance deployment

---

_config.yml

Switch to 'MAPS' branch

---

_config.yml
_config_prod.yml

Changing Twitter link to @ONS.

Twitter update

---

_config.yml

I made a second branch to merge in the changes, but this wasn't necessary as only one edit was needed.

Set up data deploy branch

---

_config.yml

Testing a deploy branch for a specific edit (in this case, [indicator 16-9-1](https://github.com/ONSdigital/sdg-data/pull/607)). In future, the Data team will use this approach to stage changes and share them with topic experts.
The URL format in _config.yml is http://sdg.mango-solutions.com/data/[BRANCH].
**Note**: This will not work with a branch containing dots (https://github.com/ONSdigital/sdg-indicators/pull/2939) - dashes only.

Set up data-deploy branch (16-9-1 test)

---

_config.yml

https://hub.arcgis.com/datasets/b7507e654334481e8e0787f42c9028c1_3

Add Country and County mapping boundaries

---

_config.yml

Update the mapping nested zoom properties.

Update mapping zoom levels

---

_layouts/indicator.html

Indicator.html - "Change data view"

---

_config.yml

Country boundaries displaying - now to edit the zoom levels to get them to display by default if applicable.
https://github.com/ONSdigital/sdg-indicators/issues/2944

Update mapping zoom level

---

scripts/deploy/deploy_testing.sh

as shown in sdg-data it's considerably faster

use rsync instead of scp

---

.gitignore
.vscode/settings.json

About time we got rid of Shane's settings

Remove vscode

---

_layouts/indicator.html

Rename embedded 'Map' tab to 'Embed'

---

_includes/assets/js/plugins/jquery.sdgMap.js
_includes/assets/js/plugins/leaflet.yearSlider.js

Testing the code of @brockfanning - https://github.com/open-sdg/open-sdg/pull/119/files

Map - skip missing years in slider 

---

_layouts/indicator.html

Reverts ONSdigital/sdg-indicators#2993
This is incompatible with Internet Explorer. Please fix this before merging again, and update the related PR in open-sdg (not merged yet): https://github.com/open-sdg/open-sdg/pull/127

Revert "Hide chart controls (disaggregations) when map or embedded map tab is clicked"

---

assets/css/default.scss

This reporting status category palette is AA standard. The text colour update on lines 1310-2 was taken from: https://github.com/ONSdigital/sdg-indicators/pull/3062.

Colour palette 3 (AA)

---

assets/css/default.scss

This reporting status category palette is AA standard. The text colour update on lines 1310-2 was taken from: https://github.com/ONSdigital/sdg-indicators/pull/3062.

Colour palette 2 (AA)

---

assets/css/default.scss

This reporting status category palette is borderline AAA standard. The text colour update on lines 1310-2 was taken from: https://github.com/ONSdigital/sdg-indicators/pull/3062.

Colour palette 1 (borderline AAA)

---

_pages/faq.md

Removed the script that adds an accordion effect to the FAQ page.

Remove accordion effect from FAQ page

---

README.md
_config.yml
_config_prod.yml

Switch to https://github.com/open-sdg/sdg-translations/releases/tag/0.5.1

Translate update

---

_layouts/indicator.html

Once it has been fixed in open-sdg, this file can be deleted

Overwriting to fix indicator code issue (for now!)

---

_includes/assets/js/indicatorView.js

https://github.com/ONSdigital/sdg-indicators/issues/3079

A11y checkbox focus fix

---

_config.yml
_includes/header.html

https://github.com/ONSdigital/sdg-indicators/issues/3082

Push to DAC branch

---

_config.yml
_includes/assets/js/accessibility.js

A contrast toggle instead of the current solution will improve screen reader compatibility.
Test branch: https://sdg.mango-solutions.com/contrasttoggle2/

[Accessibility] Contrast toggle

---

_includes/footer.html
_pages/accessibilitystatement.md
_pages/faq.md

The footer will need to be added as an `open-sdg` change somehow.
Test: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/a11y_statement/accessibility-statement/

Accessibility statement

---

_config.yml
data/translations/en/header.yml

Feature branch:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/beta-tag/
@AnnCorp @phillipgardiner here's how this looks

Change alpha to beta and accompanying text

---

_config.yml
assets/css/custom.scss

* Add UR button to banner
* Add custom styling for banner and UR button
* Remove extra white space
* Remove accidentally pasted text

Push to live

---

_config.yml
_config_prod.yml
_pages/faq.md

http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/disagg-report/reporting-status
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/disagg-report/faq

Add disaggregation report link to reporting status page and FAQ

---

_includes/components/indicator/data-notice.html
_includes/components/indicator/metadata-tabs-default.html

* Add component for change-notice
* Overwrite indicator layout to include changenotice
* Overwrite standalone-indicators with customisation
* Overwrite so global metadata shows on archived
* Overwrite data notice to meet UX recommendations
* Add style changes
* Rename _includes/components/change-notice.html to _includes/components/indicator/change-notice.html
* Move to indicator folder
* Move to indicator

Get latest changes from develop

---

_config.yml

Reverts ONSdigital/sdg-indicators#3517

Revert "Test a fix"

---

_sass/variables.scss

Feature branch: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-remove-yellow-lines/1-1-1/

Remove yellow lines on indicator pages

---

_includes/components/emergency-banner.html

changed the links titles at the bottom of the map that i could in the site config.

Update map link titles

---

_includes/custom/cookie-page-analytics.html
_pages/cookies.md
_sass/custom.scss

Fixes #3612 
Feature branch: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-cookie-page-updates/cookies/

Updates to the cookies page

---

_pages/userpersonas.md
_sass/custom.scss

Fixes #3613 
Link: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-user-personas-flex/user-personas/

Flex approach for user personas styling

---

_data/site_config.yml

FB - http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-change-reporting-status-text/reporting-status/

Change RS text

---

_pages/privacy-notice.md

http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-privacy-fix/privacy-notice/

Feature site privacy fix
